name: Build check

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 12 * * *'

permissions:
  contents: read

jobs:
  build_check:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Build check
        run: deno --allow-env --allow-read --allow-net --allow-write scrape/main.ts
